apiVersion: v2
publisher: Red Hat Developer
name: Community-Server-Connectors
version: 1.0.61
type: VS Code extension
displayName: Community Server Connectors
title: Community Server Connectors
description: Community Server Connectors
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-plugin-registry/resources/images/default.svg?sanitize=true
repository: https://github.com/redhat-developer/rsp-server-community/
category: Other
firstPublicationDate: '2020-07-30'
spec:
  extensions:
  - "https://github.com/robstryker/testRSPinCheAndTheia/raw/master/communityserverconnector/redhat.vscode-community-server-connector-0.23.7.vsix"
latestUpdateDate: "2020-07-30"
