apiVersion: v2
publisher: Red Hat Developer
name: RSPUI
version: 1.0.61
type: VS Code extension
displayName: Runtime Server Protocol UI
title: Runtime Server Protocol UI
description: Runtime Server Protocol UI
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-plugin-registry/resources/images/default.svg?sanitize=true
repository: https://github.com/redhat-developer/vscode-rsp-ui/
category: Other
firstPublicationDate: '2020-07-30'
spec:
  extensions:
  - "https://github.com/robstryker/testRSPinCheAndTheia/raw/master/rspui/redhat.vscode-rsp-ui-0.23.4.vsix"
latestUpdateDate: "2020-07-30"
