apiVersion: v2
publisher: Red Hat Developer
name: Server Connector
version: 1.0.61
type: VS Code extension
displayName: Server Connector
title: Server Connector
description: Server Connector
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-plugin-registry/resources/images/default.svg?sanitize=true
repository: https://github.com/redhat-developer/vscode-server-connector/
category: Other
firstPublicationDate: '2020-07-30'
spec:
  extensions:
  - "https://github.com/robstryker/testRSPinCheAndTheia/raw/master/serverconnector/redhat.vscode-server-connector-0.23.5.vsix"
latestUpdateDate: "2020-07-30"
